version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-browsers
    - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
    - checkout
    - run: composer install -n --prefer-dist

    - run: phpunit
  deploy:
    docker:
    - image: circleci/node:chakracore-8.11.1
    steps:
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: AWS EC2 deploy
        command: |
            scp -r -o StrictHostKeyChecking=no ./ ubuntu@3.105.35.216:/home/circleci-aws/
            ssh -o StrictHostKeyChecking=no ubuntu@3.105.35.216 "./deploy.sh"